[build]
  command = "npm install --legacy-peer-deps && npm run netlify-build"
  publish = "dist"
  NODE_VERSION = "18.17.1"  # Use specific Node.js version for better compatibility

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  NODE_ENV = "production"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# MIME type configuration
[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=31536000"

[context.production]
  command = "npm install --legacy-peer-deps && npm run netlify-build"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run netlify-build"
  environment = { NODE_ENV = "production" }

[context.branch-deploy]
  command = "npm install --legacy-peer-deps && npm run netlify-build"
  environment = { NODE_ENV = "production" }
