[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  NODE_OPTIONS = "--openssl-legacy-provider"
  CI = "false"
  
  # Firebase Configuration - These should be set in Netlify's environment variables
  VITE_FIREBASE_API_KEY = "${FIREBASE_API_KEY}"
  VITE_FIREBASE_AUTH_DOMAIN = "${FIREBASE_AUTH_DOMAIN}"
  VITE_FIREBASE_PROJECT_ID = "${FIREBASE_PROJECT_ID}"
  VITE_FIREBASE_STORAGE_BUCKET = "${FIREBASE_STORAGE_BUCKET}"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "${FIREBASE_MESSAGING_SENDER_ID}"
  VITE_FIREBASE_APP_ID = "${FIREBASE_APP_ID}"

# Required for SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  
# Handle 404s
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# MIME type headers
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

[context.production]
  command = "npm install --legacy-peer-deps && npm run build"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build"
  environment = { NODE_ENV = "production" }

[context.branch-deploy]
  command = "npm install --legacy-peer-deps && npm run build"
  environment = { NODE_ENV = "production" }
