[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  VITE_NETLIFY_CONTEXT = "$CONTEXT"
  NODE_ENV = "production"

# This is the only redirect rule needed for a Single-Page App.
# It serves the index.html file for any request that doesn't match a file
# on the server, allowing the Vue router to handle the route.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# MIME type headers
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "publish"

# Environment-specific settings
[context.staging]
  environment = { VITE_GIT_BRANCH = "staging" }

[context.testing]
  environment = { VITE_GIT_BRANCH = "testing" }
