[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  NODE_OPTIONS = "--openssl-legacy-provider"
  CI = "false"
  
  # Firebase Configuration
  VITE_FIREBASE_API_KEY = "YOUR_API_KEY_HERE"  # Replace with your actual Firebase API key
  VITE_FIREBASE_AUTH_DOMAIN = "beamtenprovi.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "beamtenprovi"
  VITE_FIREBASE_STORAGE_BUCKET = "beamtenprovi.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "719958136121"
  VITE_FIREBASE_APP_ID = "1:719958136121:web:74379fdb2c0c7c942384e8"

# Required for SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# MIME type headers
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

[context.production]
  command = "npm install --legacy-peer-deps && npm run build"
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build"
  environment = { NODE_ENV = "production" }

[context.branch-deploy]
  command = "npm install --legacy-peer-deps && npm run build"
  environment = { NODE_ENV = "production" }
