[build]
  # This command will be used by Netlify
  command = "npm install -g npm@latest && npm install --legacy-peer-deps && npm install vite@7.0.6 @vitejs/plugin-vue@5.0.0 --save-dev && npm rebuild && npm run build"
  publish = "dist"

# Add a build script in package.json that uses the local Vite binary
# "build": "vite build --config vite.config.prod.js --mode production"

# Force Netlify to use our build command
[build.environment]
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "20.19.0"  # Required by Vite 7.0.6
  NPM_VERSION = "10.5.0"    # Matches Node.js 20.19.0
  NODE_OPTIONS = "--openssl-legacy-provider"
  CI = "false"
  VITE_NETLIFY_CONTEXT = "$CONTEXT"
  NODE_ENV = "production"

# This is the only redirect rule needed for a Single-Page App.
# It serves the index.html file for any request that doesn't match a file
# on the server, allowing the Vue router to handle the route.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# MIME type headers
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "publish"

# Environment-specific settings
[context.staging]
  environment = { VITE_GIT_BRANCH = "staging" }

[context.testing]
  environment = { VITE_GIT_BRANCH = "testing" }
